# Generated by Django 5.2.1 on 2025-07-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_funcionario_user_alter_funcionario_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='senha',
        ),
    ]
