# Generated by Django 5.2 on 2025-04-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('status_disponibilidade', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('ALUGADO', 'Alugado'), ('MANUTENCAO', 'Em Manutenção')], default='DISPONIVEL', max_length=20)),
                ('preco_locacao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
