# Generated by Django 5.2 on 2025-04-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/'),
        ),
    ]
