# Generated by Django 5.2 on 2025-04-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_veiculo_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='status_disponibilidade',
            field=models.BooleanField(default=True),
        ),
    ]
