# Generated by Django 5.2.1 on 2025-06-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_alter_veiculo_status_disponibilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(default='prata', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(default='prata', max_length=100),
            preserve_default=False,
        ),
    ]
