# Generated by Django 5.2.1 on 2025-06-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_veiculo_ano_veiculo_cor_veiculo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='categoria',
            field=models.CharField(choices=[('hatch', 'Hatch'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('pickup', 'Pickup'), ('luxo', 'Luxo'), ('utilitario', 'Utilitário')], max_length=50),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='status_disponibilidade',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('alugado', 'Alugado'), ('manutencao', 'Em Manutenção')], default='disponivel', max_length=20),
        ),
    ]
