# Generated by Django 5.2.1 on 2025-07-06 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0005_alter_veiculo_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('previsao_conclusao', models.DateField()),
                ('concluida', models.BooleanField(default=False)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='manutencoes', to='veiculos.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('classe_carro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='veiculos.classecarro')),
            ],
        ),
    ]
