# Generated by Django 5.2.1 on 2025-07-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0006_classecarro_manutencao_tarifa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa',
            name='classe_carro',
        ),
        migrations.DeleteModel(
            name='ClasseCarro',
        ),
        migrations.DeleteModel(
            name='Tarifa',
        ),
    ]
