# Generated by Django 5.2 on 2025-04-16 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_valor_total'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='reserva',
            name='nivel_combustivel_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='nivel_combustivel_inicial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='observacoes_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='observacoes_inicial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='quilometragem_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='quilometragem_inicial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('pendente', 'Pendente'), ('finalizada', 'Finalizada'), ('retirada', 'Retirada')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.funcionario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
