# Generated by Django 5.2 on 2025-04-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_remove_reserva_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='nivel_combustivel_final',
            field=models.CharField(blank=True, choices=[('cheio', 'Cheio'), ('3/4', '3/4'), ('meio', 'Meio'), ('1/4', '1/4'), ('quase_vazio', 'Quase vazio'), ('vazio', 'Vazio')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nivel_combustivel_inicial',
            field=models.CharField(blank=True, choices=[('cheio', 'Cheio'), ('3/4', '3/4'), ('meio', 'Meio'), ('1/4', '1/4'), ('quase_vazio', 'Quase vazio'), ('vazio', 'Vazio')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('pendente', 'Pendente'), ('retirada', 'Retirada'), ('finalizada', 'Finalizada')], default='pendente', max_length=20),
        ),
    ]
