# Generated by Django 5.2.1 on 2025-06-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reserva_nivel_combustivel_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
